### PR TITLE
gdrdrv init script for ubuntu, closes #32

### LINKED ISSUE #32: create init.d/gdrdrv script for ubuntu

### PR DESCRIPTION
**Pull request by e-ago**

### CODE REVIEW

**Comment by e-ago** [comment]
@drossetti one folder for debian stuff and one folder for rhel stuff

**Comment by e-ago** [comment]
@drossetti  Is this PR ok? Or should I change something?

**Comment by drossetti** [comment]
I guess more metadata files are needed to build deb packages

**Comment by drossetti** [comment]
@pakmarkthub please review. How does this one compose with your other PR regarding packaging?

**Comment by pakmarkthub** [comment]
This PR should complement #61: Support debian and dkms packaging. 

@e-ago How do you plan for the users to install this debian init.d script? Do they need to copy it to their system init.d folder?

**Comment by pakmarkthub** [comment]
Also merged into PR #74.

**Comment by pakmarkthub** [comment]
Merged

**Pull request closed without merging**
